import { destinationHref, statusLabel, type SiteConfig } from '../recipes/immersive-website';
export const escapeHtml = (value: string) => value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
export function renderSite(c: SiteConfig): string {
  const e = escapeHtml;
  const actions = (ids: string[] = []) => ids.map(id => { const a = c.actions.find(x => x.id === id)!; return `<a class="button ${a.emphasis}" href="${e(destinationHref(a.destination))}">${e(a.label)} <span aria-hidden="true">↗</span></a>`; }).join('');
  const media = (ids: string[] = []) => ids.map(id => {
    const m = c.media.find(x => x.id === id)!;
    if (m.kind === 'image') return `<img loading="lazy" src="${e(m.src)}" alt="${e(m.alt)}" width="${m.width}" height="${m.height}">`;
    const poster = c.media.find(x => x.id === m.posterMediaId)!;
    return `<figure><video controls preload="none" aria-label="${e(m.title)}" poster="${e(poster.src)}" src="${e(m.src)}">${m.captions.map(t => `<track kind="captions" src="${e(t.src)}" srclang="${e(t.language)}" label="${e(t.label)}">`).join('')}</video><figcaption>${e(m.title)}</figcaption><details><summary>Transcript</summary><p>${e(m.transcript)}</p></details>${m.audioDescriptionSrc ? `<a href="${e(m.audioDescriptionSrc)}">Audio-described version</a>` : ''}</figure>`;
  }).join('');
  const hero = c.sections[0];
  const launch = c.presentation.immersive.enabled ? '<button class="button primary" data-enter hidden>Enter Immersive Experience <span aria-hidden="true">↗</span></button>' : '';
  return `<a class="skip-link" href="#main">Skip to content</a>
  <header class="site-header"><a class="brand" href="#" aria-label="${e(c.site.title)} home"><span class="brand-mark" aria-hidden="true">${e(c.site.title.split(/\s+/).slice(0, 2).map(word => word[0]).join('/'))}</span>${e(c.site.title)}</a><nav aria-label="Main navigation">${c.navigation.map(n => `<a href="${e(destinationHref(n.destination))}">${e(n.label)}</a>`).join('')}</nav></header>
  <main id="main" tabindex="-1">
    <section class="hero" id="section-${e(hero.id)}"><div class="hero-copy"><p class="eyebrow">Independent thinking. Immersive possibilities.</p><h1>${e(hero.title)}</h1>${hero.paragraphs.map(p => `<p class="lead">${e(p)}</p>`).join('')}<div class="actions">${launch}${actions(hero.actionIds)}</div><p class="quiet">Explore on your screen. Step inside when you’re ready.</p></div><div class="architectural-art" aria-hidden="true"><div class="art-grid"></div><div class="arch arch-back"></div><div class="arch arch-front"></div><div class="art-plinth"></div><div class="art-orb"></div><div class="art-caption"><span>A space for possibility</span><span>01 / INFINITE POTENTIAL</span></div></div></section>
    <div class="principles"><span>Web-first</span><span>Accessible by design</span><span>Spatial by possibility</span></div>
    ${c.sections.slice(1).map((s, index) => `<section class="content-section" id="section-${e(s.id)}" aria-labelledby="heading-${e(s.id)}"><div class="section-intro"><p class="eyebrow">0${index + 1} / ${e(s.id.replace(/-/g, ' '))}</p><h2 id="heading-${e(s.id)}" tabindex="-1">${e(s.title)}</h2>${s.paragraphs.map(p => `<p>${e(p)}</p>`).join('')}</div>${s.experienceIds?.length ? `<div class="capability-grid">${s.experienceIds.map((id, i) => { const x = c.experiences.find(v => v.id === id)!; return `<article class="capability-card" id="experience-${e(x.id)}" aria-labelledby="title-${e(x.id)}"><div class="card-top"><span class="card-number" aria-hidden="true">${String(i + 1).padStart(2, '0')}</span><span class="badge ${x.status}">${statusLabel(x.status)}</span></div><h3 id="title-${e(x.id)}" tabindex="-1">${e(x.title)}</h3><p>${e(x.summary)}</p><details><summary>About this capability</summary>${x.paragraphs.map(p => `<p>${e(p)}</p>`).join('')}</details>${media(x.mediaIds)}${actions(x.actionIds)}${c.presentation.immersive.enabled ? `<button class="text-button" data-enter="${e(x.id)}" hidden>View exhibit <span aria-hidden="true">↗</span><span class="sr-only">: ${e(x.title)}</span></button>` : ''}</article>`; }).join('')}</div>` : ''}${media(s.mediaIds)}<div class="actions">${actions(s.actionIds)}</div></section>`).join('')}
  </main>
  <footer><a class="brand" href="#">${e(c.site.title)}</a><p>${e(c.site.description)}</p><span>ImmersiveWebsiteRecipe / v0.1</span></footer>
  <details class="preferences"><summary>Accessibility preferences</summary><label>Motion <select id="motion"><option value="system">Follow device preference</option><option value="reduced">Reduce motion</option></select></label><label><input type="checkbox" id="captions"> Prefer captions</label><button id="reset-preferences" class="text-button">Reset preferences</button></details>
  <dialog id="experience-dialog" aria-labelledby="experience-heading"><div class="experience-header"><div><p class="eyebrow">A space for possibility</p><h2 id="experience-heading">${e(c.site.title)} / Showroom</h2></div><button id="close-experience" class="button secondary">Return to website</button></div>
  <p id="experience-status" role="status">Preparing the showroom...</p>
  <div class="experience-stage"><div id="scene-container" aria-label="Interactive showroom"></div>
    <section id="portal-preview-html" class="portal-preview" aria-labelledby="portal-title" tabindex="-1" hidden><p id="portal-status" class="eyebrow"></p><h3 id="portal-title"></h3><p id="portal-summary"></p><p id="portal-message"></p><label>Portal destination <select id="portal-destination">${c.portals.map(p => { const x = c.experiences.find(x => x.id === p.experienceId)!; return '<option value="' + e(x.id) + '">' + e(x.title) + '</option>'; }).join('')}</select></label><div class="actions"><button id="portal-inspect" class="button primary">Inspect destination exhibit</button><button id="portal-back" class="button secondary">Back to showroom</button></div></section>
  </div>
  <div class="experience-toolbar"><button id="overview" class="button secondary">Overview</button><button id="previous-exhibit" class="button secondary" aria-label="Previous exhibit">Previous</button><label>Exhibit list <select id="experience-select">${c.experiences.map(x => '<option value="' + e(x.id) + '">' + e(x.title) + '</option>').join('')}</select></label><button id="next-exhibit" class="button secondary" aria-label="Next exhibit">Next</button><button id="preview-portal" class="button secondary">Explore portal</button><button id="free-explore" class="button secondary" aria-pressed="false">Free exploration</button><button id="enter-xr" class="button primary" disabled>Enter XR</button></div>
  <div class="showroom-information"><div class="exhibit-description"><p id="exhibit-status" class="eyebrow"></p><h3 id="exhibit-title"></h3><p id="exhibit-summary"></p><details><summary>Read more</summary><p id="exhibit-details"></p></details></div><div class="showroom-help"><p id="navigation-help">Choose an exhibit or use Previous / Next. Overview returns to the entrance. Select a sculpture to discover its capability.</p><label><input type="checkbox" id="showroom-motion"> Reduce environmental motion</label><p class="quiet">In XR, use teleport and snap turn. Select with trigger or pinch. The spatial panel includes Return to website.</p></div></div></dialog>`;
}
